name: Lint & Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run pylint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run linters
        run: |
          pylint ./api/*